### ISSUE TITLE
Unable to install in Python 3.4

### ISSUE THREAD

**Issue by bonedaddy** [ParallelDots/ParallelDots-Python-API#3]
See the following traceback:

pi@raspberrypi:~/ParallelDots-Python-API $ sudo python3.4 setup.py install
running install
Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
/usr/bin/python3.4 -E -c pass
TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing top-level names to ParallelDots.egg-info/top_level.txt
writing dependency_links to ParallelDots.egg-info/dependency_links.txt
writing ParallelDots.egg-info/PKG-INFO
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    'paralleldots=paralleldots:main',
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 161, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 349, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.4/distutils/dist.py", line 1108, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.4/distutils/dist.py", line 1129, in write_pkg_file
    long_desc = rfc822_escape(self.get_long_description())
  File "/usr/lib/python3.4/distutils/util.py", line 470, in rfc822_escape
    lines = header.split('\n')
TypeError: Type str doesn't support the buffer API

**Comment by Meghdeep** [comment]
The previous release ( 0.4.9 ) was not compatible with Python 3.4.
This has been remedied with the latest release ( 0.6.0 ) !
