### ISSUE TITLE
Hi, I can't use this package

### ISSUE THREAD

**Issue by Yuminzhou** [ParallelDots/ParallelDots-Python-API#9]
After installing this package (have tried both pip and python xx install method)

Error shows:

>>> from paralleldots import set_api_key, get_api_key
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "paralleldots\__init__.py", line 3, in <module>
    from paralleldots.taxonomy            import get_taxonomy            as taxonomy
  File "paralleldots\taxonomy.py", line 2, in <module>
    import requests
  File "C:\Users\yuminzhou\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "C:\Users\yuminzhou\AppData\Local\Continuum\Anaconda2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 48, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "C:\Users\yuminzhou\AppData\Local\Continuum\Anaconda2\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "C:\Users\yuminzhou\AppData\Local\Continuum\Anaconda2\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 24, in <module>
    from cryptography.hazmat.backends.openssl.ciphers import _CipherContext
  File "C:\Users\yuminzhou\AppData\Local\Continuum\Anaconda2\lib\site-packages\cryptography\hazmat\backends\openssl\ciphers.py", line 16, in <module>
    @utils.register_interface(ciphers.AEADDecryptionContext)
AttributeError: 'module' object has no attribute 'AEADDecryptionContext'

I am using Windows 7 and Python version is 2.7. Thank you for helping.

**Comment by Meghdeep** [comment]
It seems like the issue is with the requests library installed on your machine. Please run `pip install requests --upgrade`.

**Comment by Yuminzhou** [comment]
@Meghdeep Thank you. I will try it
